### ISSUE TITLE
media-libs/vapoursynth-53: Bump to Python 3.9

### ISSUE THREAD

**Issue by ALTracer** [4re/vapoursynth-portage#103]
https://github.com/4re/vapoursynth-portage/blob/f098e18b7564832586e6970cdf971aa93ee0c3c6/media-libs/vapoursynth/vapoursynth-53.ebuild#L6

Per [https://www.gentoo.org/support/news-items/2021-05-05-python3-9.html](https://www.gentoo.org/support/news-items/2021-05-05-python3-9.html) Gentoo profiles switched from python3_8 to python3_9 on 2021-06-01.

R53 declares Python 3.9 compatibility for Windows, whereas Linux Build instructions say "Any version of Python 3 will do."

Could you please bump `PYTHON_COMPAT` to `( python3_{6,7,8,9} )` following the usual dependency bump rules?

On my two systems nothing else depends on Python 3.8 (except old Blender and targetcli-fb) and I'd like to depclean `dev-lang/python:3.8` to keep Portage dependency solver functional.

**Comment by 4re** [comment]
I will do it once I get home.

**Comment by 4re** [comment]
Done.
