### ISSUE TITLE
media-video/mpv[wayland] wants mesa[egl,gbm] which are dropped

### ISSUE THREAD

**Issue by ALTracer** [4re/vapoursynth-portage#108]
https://github.com/4re/vapoursynth-portage/blob/ea60fcc551bb7fea0660f2c4657db037ff6179fd/media-video/mpv/mpv-0.33.1-r100.ebuild#L74

Since mesa-21.3.4 on Gentoo stable amd64 they've dropped the `egl` and `gbm` USE flags, enabling them by default.
https://gitweb.gentoo.org/repo/gentoo.git/commit/media-libs/mesa?id=4dd59fa7fb6e80db150d9d754cda4fd43e2a594d
The mpv ebuild, when asking for `+wayland`, requires `mesa[egl]`, which is not satisfiable for >=mesa-21.3.4.

Consider reworking dependency flags?

Also note this [media-video/mpv: Set USE-defaults for mesa[egl,gbm]](https://gitweb.gentoo.org/repo/gentoo.git/commit/media-video/mpv?id=c639d3963ccf2a12207fad765f40e80503854c91) commit

**Comment by 4re** [comment]
Synced ebuilds with Gentoo upstream, so probably fixed at b29d7c81484d2a45cdb57b9b678d4e454d3ee7f9 .

**Comment by ALTracer** [comment]
Can confirm as fixed, 0.34 builds against new mesa.
Still works under Plasma/Wayland with SVP4.
