### ISSUE TITLE
media-video/mpv[vaapi] & libva rename

### ISSUE THREAD

**Issue by ALTracer** [4re/vapoursynth-portage#116]
Gentoo upstream moved x11-libs/libva* to media-libs/libva* a week ago: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=8f7d398099da5d1fc6f9f7757c03e11e26ac154c , or on Github: https://github.com/gentoo-mirror/gentoo/commit/8f7d398099da5d1fc6f9f7757c03e11e26ac154c

https://github.com/4re/vapoursynth-portage/blob/032984901691954df754910ba8b669c01487dc6f/media-video/mpv/mpv-0.34.1-r101.ebuild#L93

I have media-video/mpv::vapoursynth in my `@world` set, and Portage complains it cannot satisfy dependencies for mpv[vaapi] as `x11-libs/libva` has gone missing. I might wanna drop the `vaapi` USE and lose my amdgpu APU h.264 decode acceleration.

Please consider renaming as well, like in 032984901691954df754910ba8b669c01487dc6f, or at least making a `|| ( x11-libs/libva media-libs/libva )`.

Otherwise this ebuild seems similar enough to in-tree https://github.com/gentoo-mirror/gentoo/blob/stable/media-video/mpv/mpv-0.34.1-r1.ebuild save for `${EPREFIX}` and ~loong.

**Comment by 4re** [comment]
Sorry I didn't check the release ebuild, should be fixed now.
