### ISSUE TITLE
media-video/mpv-9999-r1::vapoursynth

### ISSUE THREAD

**Issue by mrturcot** [4re/vapoursynth-portage#117]
Hello is there anyway we could add a build-date USE flag with meson "option('build-date', type: 'boolean', value: true, description: 'whether to include binary compile time')" because as now mpv -v shows "[cplayer]  built on UNKNOWN"

compiling manually with that option I get "[cplayer]  built on Sun Oct 30 12:34:35 2022"

Just nicer to keep track. Thanks for considering!

**Comment by eli-schwartz** [comment]
There's a build option to set it to "UNKNOWN", but the fallback is to run version.py which actually does respect SOURCE_DATE_EPOCH. (version.sh does not, but that is only used by waf).
