### ISSUE TITLE
media-libs/vapoursynth: Provide separate use flags for builtin plugins

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#12]
VapourSynth [allows to select builtin plugins separately](https://github.com/vapoursynth/vapoursynth/blob/f9f44c3797189b1d2eceb3608d0a605df56f8f13/configure.ac#L303-L310) so it would be nice to have them as separate flags since some plugins require dependencies which might be undesirable.

Great overlay, btw! Works like a charm.

**Comment by 4re** [comment]
Closed via 8208c89623afaae693e5d9d37881bce8a8d11753

Glad this overlay is useful to other fellow Gentoo users. :)

**Comment by Kagami** [comment]
Thanks!
