### ISSUE TITLE
media-plugins/vapoursynth-smoothuv "wrong" license

### ISSUE THREAD

**Issue by q3cpma** [4re/vapoursynth-portage#124]
Hello

According to:
https://github.com/dubhater/vapoursynth-smoothuv
http://avisynth.nl/index.php/SmoothUV
http://avisynth.nl/index.php/SmoothUV2
License is GPLv2. "GPL" isn't recognized by portage (look into `/usr/portage/license`), forcing the use of `package.license` to unmask, please use "GPL-2".

By the way, thanks for your continuous efforts, happy to say I can rely on your quality overlay.

**Comment by q3cpma** [comment]
Same for `media-plugins/vapoursynth-descale` and "WTFPL" instead of "WTFPL-2" (unless this is a portage problem).

**Comment by 4re** [comment]
Hi,

Thanks for making me know about this, it looks like I got some typos there. I will fix them sometime soon.

And I'm glad this overlay is useful to other people. :)
