### ISSUE TITLE
media-plugins/vapoursynth-fmtconv: Doc flag is not respected

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#13]
[fmtconv ebuild](https://github.com/4re/vapoursynth-portage/blob/master/media-plugins/vapoursynth-fmtconv/vapoursynth-fmtconv-9999.ebuild) always intalls the docs even if appropriate use flag is disabled.

As an unrelated note: is `"+doc"` considered as good practice for ebuilds? In case of vapoursynth and some other plugins it requires sphinx and other deps. It's always possible to disable of course, but I checked bunch of installed programs in my system and all of them have `"doc"` disabled.

**Comment by 4re** [comment]
Fixed via 3fa1aa92e85532e816582733af397838a76f9e99

When I started this it was only for me... and I wanted always the docs.
So in short, things like this are just leftovers from that. :P
I guess I can just add ```*/*::vapoursynth doc``` to my use flags.
I will change it maybe tomorrow, today I feel lazy.

**Comment by Kagami** [comment]
Thanks!

I'm ok with either variant, just was curious what's the common case for that.
