### ISSUE TITLE
mpv-0.35.1 build fails

### ISSUE THREAD

**Issue by ivan-boikov** [4re/vapoursynth-portage#130]
Build of 0.35.1-r100 fails with the following errors
```C
../mpv-0.35.1/video/out/vo_gpu_next.c:268:14: error: ‘struct pl_tex_transfer_params’ has no member named ‘stride_w’
  268 |             .stride_w   = item->packed->stride[0] / tex_fmt->texel_size,
      |              ^~~~~~~~
../mpv-0.35.1/video/out/vo_gpu_next.c: In function ‘draw_frame’:
../mpv-0.35.1/video/out/vo_gpu_next.c:932:14: error: ‘struct pl_queue_params’ has no member named ‘frame_duration’
  932 |             .frame_duration = frame->ideal_frame_duration,
      |              ^~~~~~~~~~~~~~
```
possibly more, but the build cannot proceed. The latest stable libplacebo-6.292.1 removed these deprecated fields, but the ebuild allows any >=libplacebo-4.202.

Is it possible to bump to/add upstream mpv-0.36? They require >=libplacebo-6.292.0 now. Alternatively, old stable libplacebo-5.264.1 still has them, so limiting to <libplacebo-6 should also work.

**Comment by 4re** [comment]
Sure thing! When I get back home today I will do it ASAP.

**Comment by ivan-boikov** [comment]
Hey @4re, I decided to try my hand at ebuild creation. This fixed compilation for me. Could you check if everything's OK?

**Comment by 4re** [comment]
Damn... sorry, I completely forgot about it...
Thanks for your contribution!
