### ISSUE TITLE
waifu2x plugins

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#14]
Would be nice to have ebuilds for [ VapourSynth-waifu2x-opt](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-waifu2x-opt) and [VapourSynth-Waifu2x-w2xc](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc) plugins too.

**Comment by 4re** [comment]
I fiddled a little with them when they appeared, but either it was a lot of work to make them work or were not working correctly. I guess I will give them another go.

**Comment by 4re** [comment]
This is just a small update, I made the ebuilds for ```VapourSynth-Waifu2x-w2xc``` but I didn't publish it because right now everything is too hackish and intrusive, also unstable. I didn't bother with ```VapourSynth-waifu2x-opt``` because it's developer said that plug-in is deprecated and way slower than the former.

I'm not sure if it is unstable because the software is wrong or something in my environment is wrong.

If you are interested, once I clean up a little the ebuild I can publish it in a separate overlay for you, because I don't feel that software is ready for general/real use.

**Comment by Kagami** [comment]
Thanks for your work! Actually I'm not that interested in these plugins, I think we can close this issue for now?

**Comment by Kagami** [comment]
It would be nice if you can share this ebuild via some gist service, for people who might be interested to build it. Overlay for just single ebuild is overhead IMO, since it's quite easy to copy ebuild file to local overlay.

**Comment by Kagami** [comment]
There is also [VapourSynth-Waifu2x-caffe](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe) now. It requires caffe (obivously) and cudnn which unfortunately are not in gentoo's official tree.

**Comment by 4re** [comment]
Not sure this is going to happen ever. cudnn is a binary blob that needs registration and some bullshit to download, so... patches are welcome. :(

**Comment by Kagami** [comment]
Gentoo has nonfree packages in official tree which require you to download blobs and put them to distfiles directory (e.g. oracle java) so I think cudnn is quite norm.

Here is my (worthless) ebuild for cudnn:

```ebuild
EAPI=5

DESCRIPTION="cudnn"
HOMEPAGE="https://developer.nvidia.com/cudnn"
SRC_URI="${PN}-7.5-linux-x64-v${PV%_*}-rc.tgz"

LICENSE=""
SLOT="0"
KEYWORDS="amd64"

S="${WORKDIR}/cuda"

src_install() {
	doheader include/*
	dolib lib*/*
}
```

It's fine to register with any fake data [here](https://developer.nvidia.com/accelerated-computing-developer) in order to be able to download latest cudnn tarball.

caffe is little harder to install. You need OpenBLAS/Atlas/MKL from e.g. [science overlay](https://github.com/gentoo-science/sci), otherwise stick to [official instructions](http://caffe.berkeleyvision.org/installation.html) - install few intree dependencies and fix variables in `Makefile.config`. I don't have ebuild for caffe, just leaving it here in case it will help someone.
