### ISSUE TITLE
vcfreq, vcmod, vcmove

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#15]
There are 3 VapourSynth plugins by vcmohan currently not available in your overlay: [vcfreq](http://forum.doom9.org/showthread.php?t=171413), [vcmod](http://forum.doom9.org/showthread.php?t=171412) and [vcmove](http://forum.doom9.org/showthread.php?t=171414). Seems like author hasn't even tried to build them on Linux and there is no VCS though, so I'm not sure they will work.

Sources:
* [General page](http://www.avisynth.nl/users/vcmohan/)
* [vcfreq](http://www.avisynth.nl/users/vcmohan/vcfreq/vcfreq_src.7z)
* [vcmod](http://www.avisynth.nl/users/vcmohan/vcmod/vcmod_src.7z)
* [vcmove](http://www.avisynth.nl/users/vcmohan/vcmove/vcmove_src.7z)

**Comment by Kagami** [comment]
Oh, there is also new [vctrans](http://www.avisynth.nl/users/vcmohan/vctrans/vctrans_src.7z).

**Comment by 4re** [comment]
That's nice, last time I checked his plug-ins source code was not available. I will give it a try and see if it compiles/works good.

**Comment by 4re** [comment]
Added vcmod, vcmove and vctrans. vcfreq does not work outside of windows as upstream explained in the main thread :( http://forum.doom9.org/showthread.php?t=171413

**Comment by Kagami** [comment]
Nice, thanks!

**Comment by Kagami** [comment]
It's also worth to add them to `Documentation/package.accept_keywords` and `sets/vapoursynth-plugins`.

**Comment by 4re** [comment]
Ouch, that slipped my mind, done.
