### ISSUE TITLE
[Gentoo] Overlay joint effort?

### ISSUE THREAD

**Issue by tokiclover** [4re/vapoursynth-portage#16]
Just stumbled on VS the other day and then started, on the spur of the moment, to include VS ebuild in [bar-overlay](https://github.com/tokiclover/bar-overay) yesterday. I am almost finished on what I wanted after a few hours...

And so found out your old overlay... I did not look at some search engines beforehand because I've heard virtually nothing for years about VS. Well, I was quite away for several years on Gentoo related activities and gave up AVS upon definitely switching to NIX and wiping away any trace of M$ OSs.

So would you be interested in a joint effort? Your ebuilds lack a certain experience sharpness in the borders... like having shared USE flag instead of the standard static-libs one... an not using a clean prefix on plugins USE flags to make it easy on the eyes and for noobs for example. And a few others minor things; however everything looks good. 

So, all in all, it was worth writing all those ebuilds from scratch in the course of a few hours... Once VS was write down, it was easy to write a few for plugins/filters/editors. Although I am eager to get TDeint+TMM pluging working and YATTA simple editors varant working which was what I used on the old days. Well, no hurry since I do no longer process video for ages because of... lack of any serious tools till... AVS/VS.

Answer?

NOTE: TDeintmod, Yadifmod and TComb do not compile here because of the function redefinition... do not have the time to look at it atm.

**Comment by tokiclover** [comment]
And yes... using media-libs for VS instead of media-video becuase FFmpeg/LibAV use that same CAT...
Well, well, nothing really.

**Comment by 4re** [comment]
Well, well, because it's planed for it to not just process video, but sound in an undetermined future.

I guess I'm OK if you want to contribute to this overlay and fix all these ebuilds as far as it does not break anything (I assume your complains about plug-ins not compiling are for the ones in your overlay, not this one).
