### ISSUE TITLE
failed to compile vapoursynth

### ISSUE THREAD

**Issue by brothermechanic** [4re/vapoursynth-portage#19]
Hello
After latest update i cannot build vapoursynth anymore
https://bpaste.net/show/f54d6941de85
Please fix it

**Comment by 4re** [comment]
Please, can you try to rebuild imagemagick package and then give vapursynth another try?

**Comment by brothermechanic** [comment]
yes, i tryed to do this, but it don't helped

**Comment by 4re** [comment]
You closed the issue but I will assume it was unintended, so I'm reopening it.

Well then, can you provide me with the output of `emerge --info media-gfx/imagemagick`?

**Comment by brothermechanic** [comment]
Sorry, accidentally.
emerge --info media-gfx/imagemagick
https://bpaste.net/show/4f94478c5de5

**Comment by 4re** [comment]
Looks like `media-gfx/imagemagick` has to be build with `+hdri` to be usable by vapoursynth. I opened an issue at vapoursynth.
You can temporarily fix it by either disabling imwr plug-in or recompiling `media-gfx/imagemagick` with `+hdri`

**Comment by dubhater** [comment]
That log is barely readable with all the colour codes...

**Comment by 4re** [comment]
Yeah, I had to download it and `less that.log`

**Comment by 4re** [comment]
If you want a clean version I think I can get the important parts unstripped.

**Comment by 4re** [comment]
@dubhater https://bpaste.net/show/0ad552ac2faa no color codes

**Comment by brothermechanic** [comment]
Thnak you for help! With hdri flag of imagemagick vapoursynth builds fine!

**Comment by 4re** [comment]
I guess it should be cosed via 10c5b6a2f1a4491d9249c5cf6873c5f28d20555f.
