### ISSUE TITLE
Remove vapoursynth-zimg?

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#27]
Since vszimg.c [is now part of vapoursynth](https://github.com/vapoursynth/vapoursynth/commit/2ce5cf5045bcc4f3dcc97c9296592dcb84659712), separate plugin for zimg is probably no longer needed? See also https://github.com/sekrit-twc/zimg/issues/37

**Comment by 4re** [comment]
Yes, but when r29 releases out, not before.

**Comment by 4re** [comment]
And we are done with this too.
