### ISSUE TITLE
vapoursynth-subtitle-9999 failed

### ISSUE THREAD

**Issue by Moiman** [4re/vapoursynth-portage#34]
!!! Digest verification failed:
!!! /var/lib/layman/vapoursynth/media-plugins/vapoursynth-subtitle/vapoursynth-subtitle-9999.ebuild
!!! Reason: Filesize does not match recorded size
!!! Got: 783
!!! Expected: 782

**Comment by 4re** [comment]
Ouch, fixed, thx for reporting.
