### ISSUE TITLE
vapoursynth-mvtools-sf-9999 Digest verification failed

### ISSUE THREAD

**Issue by Moiman** [4re/vapoursynth-portage#40]
* Digest verification failed:
 * /var/lib/layman/vapoursynth/media-plugins/vapoursynth-mvtools-sf/vapoursynth-mvtools-sf-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 957
 * Expected: 954

**Comment by 4re** [comment]
I was too naïve... Once I get home I will fix it.

**Comment by Kagami** [comment]
Oops, sorry. Completely forgot about checksums…

**Comment by 4re** [comment]
Fixed.
