### ISSUE TITLE
vapoursynth-deblock fails to emerge

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#43]
Hello, trying to emerge vapoursynth-deblock-5 fails with the following error:
```
/tmp/portage/media-plugins/vapoursynth-deblock-5/work/vapoursynth-deblock-5/Deblock/Deblock.cpp:398:56: error: could not convert ‘{std::move<DeblockData&>((* & d))}’ from ‘<brace-enclosed initializer list>’ to ‘DeblockData’
     DeblockData * data = new DeblockData{ std::move(d) };
```

**Comment by 4re** [comment]
Please, post the full output from `emerge --info media-plugins/vapoursynth-deblock` and the full ebuild log (or a link to those or anything).

**Comment by Q3CPMA** [comment]
Build log: https://a.pomf.cat/zgnmpt.log
Emerge --info: https://a.pomf.cat/zxfzcl.log

**Comment by 4re** [comment]
Sorry about the delay, I couldn't reproduce this and I'm not able to install older gcc versions in my computer (I'm using gcc-5.4).

I suggest you bring this upstream, because maybe it is a problem with gcc-4.9

**Comment by Q3CPMA** [comment]
Found the problem. It apparently switched from c++11 to c++14 in https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Deblock/commit/547f44c7a8d36c62c0d84fedd68038a7bd08ab3e which is not support by gcc-4.9. Do you think it's possible to do something automatic here?

**Comment by 4re** [comment]
Tell me if this makes the ebuild work for you https://paste.kde.org/pzkyesem7/a6vf5l https://wiki.gentoo.org/wiki//etc/portage/patches

**Comment by 4re** [comment]
But I don't think that will work at all, if so, gcc should have complained about not knowing what c++14 is.

In case it does not work, your only solution would be to use deblock-4 (I will add it again), or tell about this to upstream to see if they are interested in making the code compatible with gcc-4.9

**Comment by Q3CPMA** [comment]
Already tried the `c++1y` bit, it didn't work. I think the only sane solution is keeping v4, putting v5 in unstable (after all, gcc-5 isn't stable) and using something like `gcc-major-version` from https://devmanual.gentoo.org/eclass-reference/toolchain-funcs.eclass/ in the v5 ebuild.

**Comment by 4re** [comment]
Wellp, I guess 91727e5118720e5c7abd9b47d90d2c057eb27873 should do it.
