### ISSUE TITLE
vapoursynth-tcanny doesn't build (require c++14)

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#44]
Hello, me again with another stable gcc problem. Tried to build tcanny (required by vine) but if failed with lots of errors.
Build log: https://a.pomf.cat/jutygm.log
emerge --info: https://a.pomf.cat/zzndje.log

Seems like r6 was still c++11. Could you at least leave the r6 ebuild, please?

**Comment by 4re** [comment]
OK, no problem. As I'm already with GCC-5 I can't come back and test this stuff, so you will need to keep filling this bug reports. :P

Closed via f297933aea3ba28d16dc530c9e8ca4d7d55aba61
