### ISSUE TITLE
tcanny-6 doesn't build

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#45]
This time, it fails (and not because of lacking std support) with:
```
TCanny/TCanny.cpp: In function ‘void tcannyCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)’:
TCanny/TCanny.cpp:922:55: error: cannot convert ‘std::remove_reference<TCannyData&>::type {aka TCannyData}’ to ‘VSNodeRef*’ in initialization
     TCannyData * data = new TCannyData { std::move(d) };
                                                       ^
GNUmakefile:23: recipe for target 'TCanny/TCanny.o' failed
make: *** [TCanny/TCanny.o] Error 1
```
build.log: https://a.pomf.cat/mycktb.log
emerge --info: https://a.pomf.cat/qqzgsj.log

**Comment by 4re** [comment]
Let's see if this time it works, version 5 now.

**Comment by 4re** [comment]
Even if it works we don't know if vine will work with anything else than latest version, if so I think you are doomed until gcc-5 stabilizes.

**Comment by Q3CPMA** [comment]
Works. Too bad r6 doesn't since it looks like a significant release.

**Comment by Q3CPMA** [comment]
Vine almost works, actually. It's KNLMeansCL that doesn't ("knlm.KNLMeansCL: no compatible opencl platforms available!"). Is it supposed to work on CPU too?

**Comment by 4re** [comment]
It is, but it becomes terribly slow. I would focus on making opencl work on your machine. There is an old knlmeans ebuild on the repo for legacy devices.

**Comment by Q3CPMA** [comment]
Tried almost everything, but I think I'll stick to Dehalo_alpha. OpenCL on my rig means proprietary driver (mesa doesn't have image support yet).
Thanks for you help.
