### ISSUE TITLE
mpv-9999-r9 don't build

### ISSUE THREAD

**Issue by brothermechanic** [4re/vapoursynth-portage#46]
waf: error: no such option: --enable-enca

https://paste.pound-python.org/show/kTXgBK8gOmuTBtzCiKdt/

**Comment by 4re** [comment]
This has supposed to be fixed by c69fd9fdb13362494ac5d6e092c5044843377570 almost one month ago. Did you `layman -s vapoursynth` lately?

**Comment by brothermechanic** [comment]
You are right!
Sorry
