### ISSUE TITLE
Make knlmeanscl in havsfunc optional / don't require mesa[opencl] in knlmeanscl

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#52]
Hi. I'm having issues compiling `media-libs/mesa[opencl]` on my system. Could you please make it optional, because knlmeanscl isn't strictly required by havsfunc?

**Comment by 4re** [comment]
Mmh.. it's true that some dependencies can be problematic, but tracking dependencies for every function in this module will be madness.

I think I will fix this with the addition of some obscure use flag.

**Comment by 4re** [comment]
Now yo have `fftw` and `opencl` useflags to get ride of some deps. Should be enough for everybody.

**Comment by Kagami** [comment]
Thanks.
