### ISSUE TITLE
vf_dlopen removed from mpv

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#55]
I get:

```
waf: error: no such option: --disable-vf-dlopen-filters
 * ERROR: media-video/mpv-9999-r9::vapoursynth failed (configure phase):
```

when trying to build latest mpv.
Because of this: https://github.com/mpv-player/mpv/commit/c680cfd18a09f9a023926db0b3a90f69e8651b37

**Comment by 4re** [comment]
Should be fixed now, thx for the report.
