### ISSUE TITLE
media-video/mpv: add javascript use-flag

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#62]
mpv's recently got support for javascript scripting:
https://github.com/mpv-player/mpv/blob/v0.27.0/wscript#L306-L310

Would be nice to have use-flag for that (gentoo already has in-tree `mujs` ebuild).

**Comment by 4re** [comment]
Live ebuild synced with official portage tree via 5a3febb88126c706de5f2cc9e630cb44d4236865. Thanks for pointing this out.
