### ISSUE TITLE
media-plugins/vapoursynth-fft3dfilter-0.20150227-r1 build failure

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#65]
Hello, emerging this package gives me:
```
making executable: usr/lib/libvsfft3dfilter.so.22
Files matching a file type that is not allowed:
   usr/lib/libvsfft3dfilter.so.22
 * ERROR: media-plugins/vapoursynth-fft3dfilter-0.20150227-r1::vapoursynth failed:
 *   multilib-strict check failed!
 *
 * Call stack:
 *   misc-functions.sh, line 666:  Called install_qa_check
 *   misc-functions.sh, line 217:  Called source 'install_symlink_html_docs'
 *   80multilib-strict, line  46:  Called multilib_strict_check
 *   80multilib-strict, line  42:  Called die
 * The specific snippet of code:
 *              [[ ${abort} == yes ]] && die "multilib-strict check failed!"
```

**Comment by Q3CPMA** [comment]
Looking at the ebuild, there's a `LD=\"$(tc-getCC)\"` that should probably be `tc-getLD`.

**Comment by Q3CPMA** [comment]
Well, this must not be it, it gives errors even earlier.

**Comment by 4re** [comment]
I see, the problem seems to be Gentoo enforcing an option that checks install path to be either `lib32` or `lib64` but forbidding ambiguous `lib` in `multilib` packages.

More packages may be affected by this. Thanks for the report.

**Comment by 4re** [comment]
Latest commits should fix this and more, let me know if you find another problem like this.
