### ISSUE TITLE
waifu-converter-cpp-5.2 fetch failure

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#67]
Hello,

the new ebuild produces a fetch failure (strange that you didn't detect it with repoman). Changing
`SRC_URI="https://github.com/DeadSix27/${PN}/archive/${PV}.tar.gz -> ${PN}-${PV}.tar.gz"`
to
`SRC_URI="https://github.com/DeadSix27/${PN}/archive/v${PV}.tar.gz -> ${PN}-${PV}.tar.gz"`
(just adding a v before ${PV}) should fix it.

**Comment by 4re** [comment]
Copy paste is your enemy. :(

Thank you for the report.
