### ISSUE TITLE
vapoursynth-41 depends on imagemagick[hdri]

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#70]
Hello, trying to build the latest vapoursynth without imagemagick[hdri] gives a quite explicit error:
```
src/filters/imwri/imwri.cpp:53:2: error: #error ImageMagick must be compiled with HDRI enabled
 #error ImageMagick must be compiled with HDRI enabled
  ^~~~~
```

**Comment by 4re** [comment]
It should be fixed now. As I had that set by default could not notice. Thank you for reporting it.
