### ISSUE TITLE
KNLMeansCL no compatible opencl platforms available!

### ISSUE THREAD

**Issue by brothermechanic** [4re/vapoursynth-portage#72]
Hello
I just installed media-plugins/vapoursynth-knlmeanscl
But it work only on CPU
On OPECL (INTEL or NVIDIA) i get this error
vapoursynth.Error: knlm.KNLMeansCL: no compatible opencl platforms available!

# eselect opencl list
Available OpenCL implementations:
  [1]   intel
  [2]   mesa
  [3]   nvidia *

**Comment by 4re** [comment]
Hi and sorry for the delay.

Can you test something? Switch to mesa OpenCL implementation, reemerge the ebuild, switch to Nvidia again and try to use it again in a script. Do you get an error?

**Comment by brothermechanic** [comment]
Hello
I did what you want, but no luck(
What is your gpu? My gpu is gtx660m, opencl-1.2
Script example
```
import vapoursynth as vs
core = vs.get_core()
ret = core.imwri.Read('v08/%04d.png', firstnum=1, alpha=False)
clp = core.fmtc.bitdepth (ret, bits=32, fulls=True, fulld=True, flt=True)
clp = core.fmtc.matrix (clp, mat="601", fulls=True, fulld=True)
clp = core.knlm.KNLMeansCL(clp, d=0, a=2, s=4, h=3.2 , device_id=1)
clp = core.fmtc.bitdepth(clp, bits=8, fulls=True, flt=False)
clp.set_output ()
```

**Comment by brothermechanic** [comment]
Note, i have working luxmark benchmark on gpu opencl mode.

**Comment by 4re** [comment]
Can you post somewhere a screenshot of what this script outputs?
```python
import vapoursynth as vs
core = vs.get_core()
clip = core.std.BlankClip(format=vs.YUV444P8)
clip = core.knlm.KNLMeansCL(clip, info=True)
clip.set_output()
```

**Comment by 4re** [comment]
No responses in three weeks, I'm closing this.

Feel free to reopen it again if you find anything or have more time to collaborate. I'm currently unable to reproduce your problem locally.

There are many versions of the plugin in the overlay, some of them with different build systems. You can check if any of them solves the problem for you and report it back so I can investigate it in the future.
