### ISSUE TITLE
Add uncross plugin

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#76]
Just found this repo: https://github.com/rzumer/uncross
Might be useful to have ebuild for it too.

**Comment by 4re** [comment]
I will look into it when I have the time but as a low priority item as it looks like not a working solution reading what the author says about it in the readme.
The fact it doesn't have a non-windows friendly build script has some degree of influence too.

**Comment by 4re** [comment]
In the end I decided to not add this to the overlay.
The project seems dead and not working at all, I will keep an eye on it and if the author retakes it and makes it work I will add it.
