### ISSUE TITLE
znedi3 lacking weights

### ISSUE THREAD

**Issue by q3cpma** [4re/vapoursynth-portage#79]
Hello,

trying to use QTGMC, I get `vapoursynth.Error: znedi3: error reading weights`. After reading the program source, here's a patch to solve it cleanly (the weights would need to have the same parent dir as the plugin, otherwise). It also installs the weights if they're not already here.
There's another problem, the X86 make variable isn't set, negating all the speed improvements of znedi3; I set it manually, but this is probably not the right way to do it.

```
--- /var/db/repos/vapoursynth/media-plugins/vapoursynth-znedi3/vapoursynth-znedi3-0.2017.11.08.ebuild	2017-12-16 18:56:39.134568056 +0100
+++ vapoursynth-znedi3-0.2017.11.08-r1.ebuild	2018-10-30 00:05:46.591720394 +0100
@@ -1,4 +1,4 @@
-# Copyright 1999-2017 Gentoo Foundation
+# Copyright 1999-2018 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=6
@@ -21,7 +21,16 @@
 DEPEND="${RDEPEND}
 "
 
+src_compile() {
+	emake CPPFLAGS="-DNNEDI3_WEIGHTS_PATH=\\\"\"${EROOT}usr/share/nnedi3/nnedi3_weights.bin\"\\\"" X86=1
+}
+
 src_install() {
 	insinto "/usr/$(get_libdir)/vapoursynth/"
 	doins vsznedi3.so
+	if [ ! -f "${EROOT}usr/share/nnedi3/nnedi3_weights.bin" ]
+	then
+		insinto "/usr/share/nnedi3"
+		doins nnedi3_weights.bin
+	fi
 }
```

**Comment by 4re** [comment]
Hi and thank you for reporting in your findings.
As soon as I have a little time I will try to apply a fix to this, this sure was a sloppy job on my side with this ebuild.

**Comment by 4re** [comment]
It must be solved now.

Because no other archs are actually supported by my ebuilds there is no reason to not activate the optimizations, but I think installing weights in the same path another ebuild installs them was not a good idea.

Thank you for your detailded bug report and don't hestitate to reopen it again if you find anything else.
