### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by brothermechanic** [4re/vapoursynth-portage#8]
Hello
I just install vapoursynth from you overlay and try to do something like i did in avisynth a long time ago.
All was great! 
Very easy install!
Software works a clockwork!
Thank you for supporting gentoo overlay!
Hope this will be in portage soon.

**Comment by 4re** [comment]
Glad you like it, but don't expect to see this in portage.
@olifre did try to put vapoursynth in portage but the lack of maintainers made his ebuilds just stall in the bug tracker forever.
Maybe it is a little inconvenient but I'm good with the way things are right now.
